Add migration guide from 2.x to 3.x
twilio/voice-quickstart-objc pull request #126
Opened 2018-10-04 01:11 UTC by bchen-twilio

Migration guide from 2.x to 3.x
- `TVOCallInvite` Changes
- Specifying a media region
- `TVOConnectOptions` & `TVOAcceptOptions`
- Ringing
- Audio Device
- Custom Parameters

2018-10-04 04:22 UTC, kbagchiGWC commented on README.md
> +`callInvite.customParameters`:
Add some text here - android says `callInvite.getCustomParameters() returns a map of key-value pair passed in the TwiML.`

2018-10-04 22:30 UTC, kbagchiGWC approved these changes

2018-10-05 23:08 UTC, idelgado requested changes

2018-10-05 23:08 UTC, idelgado commented on README.md
> +## Migragion Guide
Migration

2018-10-05 23:08 UTC, idelgado commented on README.md
> +
Please add a section for https://github.com/twilio/voice-quickstart-android/tree/3.x#media-establishment--connectivity

2018-10-05 23:40 UTC, idelgado approved these changes

2018-10-10 06:07 UTC, piyushtank commented on README.md
> +The Voice iOS 3.X SDK deprecates the `CallKitIntegration` category from `TwilioVoice` in favor of a new property called `TVODefaultAudioDevice.enabled`. This property provides developers with a mecha
sentense has a typo
`s/A Cal can/A Call can`

2018-10-10 06:13 UTC, piyushtank approved these changes

2018-10-10 06:16 UTC, merged