Add microphone permission guideline in the migration guide
twilio/voice-quickstart-objc pull request #135
Opened 2018-12-05 21:13 UTC by bchen-twilio

Add a section in the migration guide for requesting microphone permission in the apps using 3.x SDK.

2018-12-06 18:08 UTC, idelgado requested changes

2018-12-06 18:08 UTC, idelgado commented on README.md
> +- (void)makeCall {
Add this logic to the quickstart code itself.

2018-12-06 18:08 UTC, idelgado commented on README.md
> +Microphone permission is not optional in the Voice iOS 2.X SDK. Permission must be granted by the user in addition to the usage description being presented in the plist file. Error will be raised whe
Lets rephase to the following 

> Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the call will connect even when the microphone permission is denied or disabled by the user. To ensure the microphone permission is enabled prior to making or accepting a call you can add the following to request permission beforehand:

2018-12-07 00:01 UTC, idelgado requested changes

2018-12-07 00:01 UTC, idelgado commented on README.md
> +Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the call will connect even when the microphone permission is denied or disabled by the user. To ensure the mic
> to request the permission beforehand:

2018-12-07 00:08 UTC, idelgado approved these changes
👍 with respect to docs. @piyushtank should review the snippet source and quickstart source.

2018-12-07 00:55 UTC, piyushtank approved these changes
Looks good. left a minor comment.

2018-12-07 00:55 UTC, piyushtank commented on ObjCVoiceQuickstart/ViewController.m
> +                                                                         style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) {
new line at `handler:`
applies to other places also

2018-12-07 00:55 UTC, piyushtank commented on ObjCVoiceQuickstart/ViewController.m
> +    TVOConnectOptions *connectOptions = [TVOConnectOptions optionsWithAccessToken:[self fetchAccessToken] block:^(TVOConnectOptionsBuilder *builder) {
new line before `block:` for readability

2018-12-07 00:55 UTC, piyushtank commented on README.md
> +Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the call will connect even when the microphone permission is denied or disabled by the user. To ensure the mic
s/call/Call

suggestions:

Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the Call will connect even when the microphone permission is denied or disabled by the user`, and the SDK will play the remote audio`. To ensure the microphone permission is enabled prior to making or accepting a call you can add the following to request the permission beforehand:

2018-12-07 02:13 UTC, piyushtank approved these changes

2018-12-07 02:13 UTC, piyushtank commented on README.md
> +Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the call will connect even when the microphone permission is denied or disabled by the user, and the SDK will
s/call/Call

2018-12-07 02:24 UTC, bobiechen-twilio commented on README.md
> +Unlike Voice iOS 2.X SDKs where microphone permission is not optional in Voice 3.X SDKs, the call will connect even when the microphone permission is denied or disabled by the user, and the SDK will
Decided to go as is based on oral discussion.

2018-12-07 02:25 UTC, merged