Updates for Voice 2.0.0-beta19 release
twilio/voice-quickstart-objc pull request #65
Opened 2017-10-24 21:56 UTC by bchen-twilio

- Use `beta19` in Podfile
- `sharedInstance` is removed from `TwilioVoice`
- Update `TVOCallDelegate` methods

2017-10-24 22:06 UTC, idelgado requested changes
Minor nitpick

2017-10-24 22:06 UTC, idelgado commented on ObjCVoiceCallKitQuickstart/ViewController.m
> +    [TwilioVoice setModule:TVOLogModulePJSIP logLevel:TVOLogLevelVerbose];
I don't think we should set this to verbose by default in the quickstart. Seems quite noisy.

2017-10-24 23:24 UTC, idelgado approved these changes

2017-10-24 23:28 UTC, merged

2017-10-25 18:39 UTC, ceaglest commented on ObjCVoiceCallKitQuickstart/ViewController.m
> +        self.callKitCompletionCallback(NO);
No need to fire the callback here, we are expecting a `didConnect` before a `didDisconnect`.

2017-10-25 18:39 UTC, ceaglest commented on ObjCVoiceCallKitQuickstart/ViewController.m
> +    [self callDisconnected];
We should fire `self.callKitCompletionCallback(NO)` within this callback, just like we did prior to this PR.